default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: eraofchange_production
  
test:
  <<: *default
  database: eraofchange_test

production:
  <<: *default
  database: eraofchange_production
  username: deploy
  password: <%= ENV["ERAOFCHANGE_DATABASE_PASSWORD"] %>
