default: &default
  adapter: postgresql
  host: localhost
  username: redmine
  password: gfhjkm
  encoding: utf8

development:
  <<: *default
  database: eraofchange_development
  
test:
  <<: *default
  database: eraofchange_test

production:
  <<: *default
  database: eraofchange_production
  username: deploy
  password: <%= ENV["ERAOFCHANGE_DATABASE_PASSWORD"] %>
